const express = require("express");
const router = express.Router();
const middleware = require("../middleware/auth.middleware");
const dashboardRouter = require("./dashboard.router");
const userAdminRouter = require("./userAdmin.router");
const userClientRouter = require("./userClient.router");
const productAdminRouter = require("./product.router");
const productClientRouter = require("./productClient.router");
const orderRouter = require("./order.router");
const bannerRouter = require("./banner.router");
const roleRouter = require("./role.router");
const cartRouter = require("./cart.router");
const myListRouter = require("./myList.router");
module.exports = (app) => {
  app.use("/auth", userAdminRouter);
  app.use("/authClient", userClientRouter);
  app.use("/product", middleware.auth, productAdminRouter);
  app.use("/productClient", productClientRouter);
  app.use("/banner", middleware.auth, bannerRouter);
  app.use("/role", middleware.auth, roleRouter);
  app.use("/dashboard", middleware.auth, dashboardRouter);
  app.use("/cart", middleware.auth, cartRouter);
  app.use("/myList", middleware.auth, myListRouter);
  app.use("/order", middleware.auth, orderRouter);
};
